---
- name: Converge
  hosts: all
  vars:
    nginx_ssl_dhparam_size: 1024
  tasks:
    - name: "Include nginx"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
